apiVersion: apps/v1
kind: Deployment
metadata:
  name: kob
  namespace: kube-system
  labels:
    app: kob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kob
  template:
    metadata:
      labels:
        app: kob
    spec:
      securityContext:
        fsGroup: 2000
      serviceAccountName: kob
      initContainers:
      - name: migration
        image: lannparty/kob-migration:1.0.5
        command: ['/bin/bash', '-c', 'liquibase --changelog-file=db/changelogs/db.changelog-root.yaml --url=jdbc:sqlite:/opt/kob/obituaries.db update']
        volumeMounts:
        - mountPath: "/opt/kob"
          name: kob
      containers:
      - name: archiver
        image: lannparty/kob-archiver:1.0.5
        volumeMounts:
        - mountPath: "/opt/kob"
          name: kob
      - name: reclaimer
        image: lannparty/kob-reclaimer:1.0.5
        volumeMounts:
        - mountPath: "/opt/kob"
          name: kob
      volumes:
      - name: kob
        persistentVolumeClaim:
          claimName: kob
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kob
  namespace: kube-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kob
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kob
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kob
subjects:
- kind: ServiceAccount
  name: kob
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kob
  apiGroup: ""
