apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-obituaries
  namespace: kube-system
  labels:
    app: kube-obituaries
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-obituaries
  template:
    metadata:
      labels:
        app: kube-obituaries
    spec:
      containers:
      - name: kube-obituaries
        image: lannparty/kube-obituaries:1.0.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-obituaries
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system
  name: kube-obituaries
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-obituaries
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: kube-obituaries
  namespace: kube-system
roleRef:
  kind: Role
  name: kube-obituaries
  apiGroup: ""
